[workspace]
members = [
  # "examples",
  "javascriptcore",
  "javascriptcore/sys",
  "webkit2gtk",
  "webkit2gtk/sys",
  "webkit2gtk-webextension",
  "webkit2gtk-webextension/sys",
]

exclude = ["gir"]
